export const SET_LOADING = "SET_LOADING";
export const SET_API_ERROR = "SET_API_ERROR";
export const SET_API_SUCCESS = "SET_API_SUCCESS";
export const SET_ADMIN_DETAILS = "SET_ADMIN_DETAILS";
export const SET_ADMIN_ROUTES = "SET_ADMIN_ROUTES";